version: '3'
services:
  app-local:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: local
    volumes:
        - .:/app
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: deploy
